[package]
name = "netwatching-aggregator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-rt = "2.9"
futures = "0.3.29"
itertools = "0.12.0"
